openapi: 3.1.0
info:
  title: CodeAPI Plugin
  description: Run program code such as python to output the analysis about datasets. Use it whenever a user want to analyze datasets such as json, csv, long text. the program code must output the analysis to stdout. An input of this api is always JSON format.
  version: 1.0.0
  servers:
    - url: ${api_base}
paths:
  /api/run:
    post:
      summary: Run code
      description: Run program code. program code should output the results to stdout.
      operationId: run_code
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RunRequest"
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/text:
              schema:
                $ref: "#/components/schemas/RunResponse"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
      security:
        - HTTPBearer: []
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: "#/components/schemas/ValidationError"
    RunRequest:
      title: RunRequest
      required:
        - language
        - code
      type: object
      properties:
        language:
          title: Programming Language
          type: string
        code:
          description: program code
          title: Code
          type: string
    RunResponse:
      title: RunResponse
      description: stdout of program code.
      type: string
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
